### ISSUE TITLE
New tile on landing page to new edition

### ISSUE THREAD

**Issue by linxOD** [karl-kraus/wpn-static#114]
Tile links to an overview page further linking to the new edition.

Overview Page:
- Link to edition
- Intro text

**Comment by linxOD** [comment]
@BOberreither can you add a new XML in gitlab:meta folder similar to e.g. annotierte_lesefassung.xml for the "typography edition"?

**Comment by BOberreither** [comment]
Sure, [here](https://gitlab.oeaw.ac.at/acdh-ch/ace/dritte-walpurgisnacht/walpurgisnacht-ende-2020/-/blob/master/meta/topographical.xml).
