### ISSUE TITLE
transcr.: rend attribute values

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#117]
`@rend` in subst / add / del
See pages [71ff.](https://karl-kraus.github.io/wpn-static/idPb0071.html)

- [x] marginRight - center of right margin
- [x] marginOuterRight - more to the edge of the page
- [x] marginInnerRight - more to the text
- [x] marginRightBelow - below "normal" marginRight, 1 font height
- [x] marginRightAbove - above "normal marginRight, 1 font height
- [x] marginLeft - see above, accordingly
- [x] marginOuterLeft
- [x] marginInnerLeft
- [x] marginLeftBelow
- [x] marginLeftAbove

- [ ] (tbc)

**Comment by linxOD** [comment]
added handling for example page 71 for tei:add and tei:del
if metamarks require this as well, please let me know.
