### ISSUE TITLE
provide links for "kommentar" menu

### ISSUE THREAD

**Issue by babslgam** [karl-kraus/wpn-static#129]
@BOberreither could you please provide the links for the "kommentar" section in the navigation menu?
![image](https://github.com/user-attachments/assets/8523dbe3-addf-45b6-b984-f407405867bf)

**Comment by BOberreither** [comment]
Sure: 
[Zu Kommentar und Zeitleiste](https://kraus1933.ace.oeaw.ac.at/kommentar.html)


[Register der Kommentare](https://kraus1933.ace.oeaw.ac.at/Gesamt.xml?template=register_kommentare.html) (else: Kommentarregister)


[Zeitleiste](https://kraus1933.ace.oeaw.ac.at/ereignisse.html)
