### ISSUE TITLE
reading version: intertext index, missing kwics

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#138]
In the original versions, texts quoted indirectly were also linked to the passage in DW from the intertext index, via a kwic. See, e.g., [this text](https://kraus1933.ace.oeaw.ac.at/Gesamt.xml?template=register_intertexte.html&letter=G#DWbibl03050), which is quoted in a newspaper. Only the newspaper is directly linked to the Gesamt.xml, and itself in turn refers to the text in question. Still, both need to have a link to Gesamt.xml from text index.
Currently not the case e.g. [here](https://karl-kraus.github.io/wpn-static/register_intertexte.html?letter=G#DWbibl03050).

**Comment by babslgam** [comment]
results should be more adequate now.

**Comment by BOberreither** [comment]
@babslgam Looks good! Just one thing I noticed: The comment-character (the Hakerl) shows in the kwic.
