### ISSUE TITLE
reading version: multiple metamark target values?

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#147]
Can a metamark function="insertion" have multiple values in target? 
e.g. line 10816 shows a couple of these: 
```
<metamark change="#inkOnProofKK" function="insertion" target="#note0195bc_1" rend="marginOuterLeft">195 b, c, </metamark>`
```
I'd like to exchange it for one with all the values in one target attribute, like:
```
<metamark change="#inkOnProofKK" function="insertion" target="#note0195bc_1 #note0195d_1 #note0195e_1 #note0195fg_1" rend="marginOuterLeft">195 b, c, d, e, <lb/>f, g</metamark>
```
Is that possible?

**Comment by BOberreither** [comment]
There is no extra linebreak to be added, the lb only indicates that Kraus had to use two lines in the margin for the metamark. Does that solve the problem?

**Comment by babslgam** [comment]
yes. 
can you please push an updated version?

**Comment by BOberreither** [comment]
@babslgam done!

**Comment by BOberreither** [comment]
@babslgam Works perfectly, just one thing: In some places, double pipes appear too often, see img.
![MultiPipes](https://github.com/user-attachments/assets/f1f8af78-6cbc-4531-adc4-5332a3c6cffb)

**Comment by babslgam** [comment]
@BOberreither should be fixed now.

**Comment by BOberreither** [comment]
@babslgam Looks good! Just one thing I noticed: The comment-character (the Hakerl) shows in the kwic.
