### ISSUE TITLE
transc.: Strange switch of text passages

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#28]
p. 190: 
https://karl-kraus.github.io/wpn-static/idPb0190.html

The longquote ("Ich jüdisches ...") jumped down somehow ... 
- [ ] misplaced longquote
- [ ] " ... Freidenker" should be justified
- [ ] "Und wäre" should follow "Vaterunser"
- [ ] missing linebreak after "Austilgund aller"

![issue1](https://github.com/user-attachments/assets/b0c754c4-3401-4a7b-a3d4-8293c1c5794c)

**Comment by linxOD** [comment]
@BOberreither please check after next buiild if this still exists.
