### ISSUE TITLE
transcr.: erratic linebreaks and missing text justification

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#29]
see p. 188: https://karl-kraus.github.io/wpn-static/idPb0188.html

![issue2](https://github.com/user-attachments/assets/5df4e9d3-f285-45d9-8406-ac1f5836ddef)

Probably has to do with 
a) del element: text herein is not justified, maybe? 
b) del element: lb in del messes with justification of rest of the line as well?
c) quote elements: quote elements spanning a p element but also some of the following running text maybe induce (wrong) linebreaks?

**Comment by linxOD** [comment]
@BOberreither please check after next build if it still exists.
