### ISSUE TITLE
transcr.: typewriter quote font size

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#34]
See, e.g., https://karl-kraus.github.io/wpn-static/idPb0059_a.html
Font size of typewriters is always the same, quote or metamark or text ...

**Comment by linxOD** [comment]
The smaller parts of the text are "typescriptLongQuote" and therefore rendered smaller than the rest of the text. In all other pages this corresponds to the facsimile.

**Comment by BOberreither** [comment]
"typescriptLongQuote" is not smaller than other typescript renditions (since typewriters had only one font size), so typescript letters should be the same font size in the whole document.

**Comment by BOberreither** [comment]
@linxOD 
Seems to work [here](https://karl-kraus.github.io/wpn-static/idPb0059_a.html) and [here](https://karl-kraus.github.io/wpn-static/idPb0195_a.html)
but not [here](https://karl-kraus.github.io/wpn-static/idPb0195_bc.html) and [here](https://karl-kraus.github.io/wpn-static/idPb0195_d.html), etc. I think it's because of the rendition "typescriptLongQuoteIndent" which should be treated like all the other typescript renditions.

**Comment by linxOD** [comment]
Note. The reading version contains rules to set "typescriptLongQuoteIndent" to 75% of the regular font size. I changed it now for this version.
