### ISSUE TITLE
transcr.: one very special page

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#47]
P. [267](https://karl-kraus.github.io/wpn-static/idPb0267.html?) has a lot of different formats - and issues, some of them because of not yet specified element treatment. Maybe a good opportunity to tackle them.
Here is a list:
- [ ] 1st line: n="last" in nb seems not to work - should be a flush line
- [x] text block "Romantik holt ..." - should be justified.
- [x] additions displayed twice: pretty much all of them, maybe because of double att. rend (in add and subst)? See [Treatment-list](https://github.com/karl-kraus/wpn-static/issues/32).
- [x] additions placed on wrong height: left: ". F", right "bei", ", König, Kaiser""
- [ ] one unnecessary line after every lg-Element
- [ ] additional line breaks: above, 3rd text block, after "Dürgoy", below, text block "Romantik ...", after "konfus"
- [ ] (Just for further notice: fw-Elements are missing, also: metamarks.)

**Comment by linxOD** [comment]
related to #91
