### ISSUE TITLE
transcr.: XML line breaks turn into HTML white space

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#68]
See for example [this page, first lines](https://karl-kraus.github.io/wpn-static/idPb0069.html) - corresponds to [this XML code](https://gitlab.oeaw.ac.at/acdh-ch/ace/dritte-walpurgisnacht/walpurgisnacht-ende-2020/-/blob/master/Gesamt.xml?ref_type=heads#L4311). Here I tried to fix the line break- and indent- unfriendly XML coding for better readability. 
Can you make sure line breaks aren't processed as white spaces? Would help improve XML quality a lot. 
Thanks!

**Comment by linxOD** [comment]
I added some extra whitespace handling but the break before and after `subst` must be removed in order to display the data proberly. 

```XML
<lb/>für d<subst change="#inkOnProofKK" rend="marginLeft">
	          <del>d</del>
	          <add xml:id="idPb0068-add-d72e234">a</add>
                </subst>s Verständnis von Dingen, die 
```
