### ISSUE TITLE
transcription: first line indent

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#7]
Please add first line indent (like in existing reader's view) for renditions:
runningText1
longQuoteIndent
longQuoteStartIndent
longQuoteMiddleIndent
longQuoteEndIndent
typescriptRunningText1
typescriptLongQuoteIndent

**Comment by linxOD** [comment]
I noticed. The issue are the preceding `lb` elements that create an extra linebreak before the first text line. The indent is there but for an empty line. Haven't figured out how to remove these first lb elements yet.

**Comment by BOberreither** [comment]
What's the solution in reader's view?

**Comment by linxOD** [comment]
The linebreaks in the readers view are not based on lb elements of the xml but break on a specified line width which does not correspond the the facsimile. Therefore they are now issue.
