### ISSUE TITLE
transcr.: missing white spaces

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#81]
See [p. 42:](https://karl-kraus.github.io/wpn-static/idPb0042.html) 
"Doch genug jetzt⁠ ⁠!nicht mehr weiter so⁠ ⁠!Welt es ver-" and so on - there are spaces missing after exclamation marks.
Also on [page 74](https://karl-kraus.github.io/wpn-static/idPb0074.html), after the question mark in the last line (note element).

But another thing: on typescript pages (see pb type), please ignore <c type="nnbsp"/>. Do not display them as a space.

**Comment by linxOD** [comment]
fixed
