### ISSUE TITLE
transcr.: empty extra lines and strange line spacing

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#82]
On page [58](https://karl-kraus.github.io/wpn-static/idPb0058.html), [59](https://karl-kraus.github.io/wpn-static/idPb0059.html), [60](https://karl-kraus.github.io/wpn-static/idPb0060.html) and others there are extra lines introduced (without text), on [page 145](https://karl-kraus.github.io/wpn-static/idPb0145.html) it's probably because of the mod element. 
And there is strange line spacing e.g. on [page 141b](https://karl-kraus.github.io/wpn-static/idPb0141_b.html)

**Comment by linxOD** [comment]
related to #91

**Comment by linxOD** [comment]
I removed extra letter-spacing and all are now 2.5px as they are in the reading version.
